PoneySeller/PoneySeller/Models/Jumbotron.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PoneySeller.Models
{
    public class Jumbotron
    {
        public int IDImage { get; set; }

      public Jumbotron()
      {
         IDImage = 1;
         Refresh();
      }

      public void Refresh()
      {
         IDImage = GetAleatoire();
      }

      public int GetAleatoire()
      {
         Random rdn = new Random();
         int math = rdn.Next(1, 10);


         return math;
      }
    }
}

PoneySeller/PoneySeller/Controllers/GestionController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PoneySeller.Controllers
{
    public class GestionController : Controller
    {
        [HttpPost]
        public ActionResult Profil(String TB_Fullname, String TB_Adresse, String TB_Ville, String TB_Telephone, String TB_Password, String TB_PasswordConfirm)
        {
            PoneySeller.Models.Users desUsagers = new PoneySeller.Models.Users(Session["MyPonies"]);
            desUsagers.SQLTableName = "Usagers";

            desUsagers.SelectByFieldName("Email", Session["Username"].ToString());

            desUsagers.Next();

            if (TB_Fullname != "" && TB_Adresse != "" && TB_Ville != "" && TB_Telephone != "" && TB_Password != "" && TB_PasswordConfirm != "")
            {
                desUsagers.usager.NomComplet = TB_Fullname;
                desUsagers.usager.Adresse = TB_Adresse;
                desUsagers.usager.Ville = TB_Ville;
                desUsagers.usager.Telephone = TB_Telephone;
                desUsagers.usager.Password = TB_Password;

                desUsagers.Update();

                ViewBag.UpdateSuccess = "Votre compte a été modifié";
            }
            else
            {
                ViewBag.ErreurVide = "Tout les champs doivent être remplis et au moins une photo doit être choisi.";
            }
            return View(new PoneySeller.Models.Jumbotron());
        }

        public ActionResult Profil()
        {
            if ((bool)Session["UserValid"])
            {
                PoneySeller.Models.Users desUsagers = new PoneySeller.Models.Users(Session["MyPonies"]);
                desUsagers.SQLTableName = "Usagers";

                desUsagers.SelectByFieldName("Email", Session["Username"].ToString());

                desUsagers.Next();

                ModelState.SetModelValue("TB_Fullname", new ValueProviderResult(desUsagers.usager.NomComplet, string.Empty, new CultureInfo("en-US")));
                ModelState.SetModelValue("TB_Adresse", new ValueProviderResult(desUsagers.usager.Adresse, string.Empty, new CultureInfo("en-US")));
                ModelState.SetModelValue("TB_Ville", new ValueProviderResult(desUsagers.usager.Ville, string.Empty, new CultureInfo("en-US")));
                ModelState.SetModelValue("TB_Telephone", new ValueProviderResult(desUsagers.usager.Telephone, string.Empty, new CultureInfo("en-US")));
                ModelState.SetModelValue("TB_Password", new ValueProviderResult(desUsagers.usager.Password, string.Empty, new CultureInfo("en-US")));
                ModelState.SetModelValue("TB_PasswordConfirm", new ValueProviderResult(desUsagers.usager.Password, string.Empty, new CultureInfo("en-US")));
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }

            return View(new PoneySeller.Models.Jumbotron());
        }

        public ActionResult Gestion(int? _idcheval)
        {
            ViewBag.Update = "non";
            PoneySeller.Models.Users desUsagers = new PoneySeller.Models.Users(Session["MyPonies"]);
            string commande = "select id from chevaux where id = " + _idcheval + "and idproprio = (select id from usagers where email = '" + Session["Username"].ToString() + "')";
            if (Session["Username"].ToString() == "" && !(bool)Session["UserValid"] && !desUsagers.ExecuteCommandBoolReturn(commande))
            {
                return RedirectToAction("Index", "Home");
            }
            ViewBag.IdDuCheval = 1;

            if (_idcheval != null)
            {
                ViewBag.Update = "oui";
                int ID = _idcheval.GetValueOrDefault();
                ViewBag.IdDuCheval = ID;
                String[] InfoCheval = desUsagers.GetInfoChevaux(ID);

                ModelState.SetModelValue("TB_Nom", new ValueProviderResult(InfoCheval[0], string.Empty, new CultureInfo("en-US")));
                ModelState.SetModelValue("TB_Age", new ValueProviderResult(InfoCheval[1], string.Empty, new CultureInfo("en-US")));
                ModelState.SetModelValue("RB_Sexe", new ValueProviderResult(InfoCheval[2], string.Empty, new CultureInfo("en-US")));
                ModelState.SetModelValue("TB_Prix", new ValueProviderResult(InfoCheval[3], string.Empty, new CultureInfo("en-US")));
                ModelState.SetModelValue("TB_Race", new ValueProviderResult(InfoCheval[4], string.Empty, new CultureInfo("en-US")));
                ViewBag.Image1 = InfoCheval[5];
            }
            else
            {
                ViewBag.Image1 = "BasePicture.png";
            }
            return View(new PoneySeller.Models.Jumbotron());
        }

        [HttpPost]
        public ActionResult Gestion(String TB_Nom, String TB_Age, String RB_Sexe, String TB_Prix, HttpPostedFileBase FileUpload1, String TB_Update, String TB_IDCheval,
                                    String CB_Discipline, String TB_Race, String btn)
        {
            if (btn == "Enregistrer")
            {
                if (TB_Nom != "" && TB_Age != "" && RB_Sexe != "" && TB_Prix != "" && CB_Discipline != "" && TB_Race != "")
                {
                    string commandesql = "";
                    if (TB_Update == "non")
                    {
                        PoneySeller.Models.Users desUsagers = new PoneySeller.Models.Users(Session["MyPonies"]);
                        int IDProprio = desUsagers.GetID(Session["Username"].ToString());
                        commandesql = "insert into chevaux (nom, age, race, prix, sexe, idproprio, photoguid) values ( '" + TB_Nom + "'," + TB_Age + ",'" + TB_Race + "', " + TB_Prix + ", '" + RB_Sexe + "', " + IDProprio + ", '" + FileUpload1.FileName.ToString() + "')";
                        if (ExecuteCommande(commandesql) > 0)
                        {
                            ViewBag.Reussi = "Cheval ajouté !";
                        }
                        else
                        {
                            ViewBag.NonReussi = "Erreur dans l'enregistrement du cheval !";
                        }
                    }
                    else if (TB_Update == "oui")
                    {
                        commandesql = "update chevaux set nom = '" + TB_Nom.ToString() + "', " +
                                                         "race = '" + TB_Race.ToString() + "', " +
                                                         "age = " + TB_Age.ToString() + ", " +
                                                         "prix = '" + TB_Prix.ToString() + "', " +
                                                         "sexe = '" + RB_Sexe.ToString() + "', " +
                                                         "photoguid = '" + FileUpload1.FileName.ToString() + "' " +
                                                         "where ID = " + TB_IDCheval;

                        if (ExecuteCommande(commandesql) > 0)
                        {
                            ViewBag.Reussi = "Cheval Modifié !";
                        }
                        else
                        {
                            ViewBag.NonReussi = "Erreur dans la modifcation du cheval !";
                        }
                    }
                }
                else
                {
                    ViewBag.ErreurVide = "Tout les champs doivent être remplis et au moins une photo doit être choisi.";
                }
            }
            else if (btn == "Supprimer")
            {
                string commandesql = "DELETE from Chevaux where id = " + TB_IDCheval;
                if (ExecuteCommande(commandesql) > 0)
                {
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    ViewBag.NonReussi = "Erreur dans la suppression du cheval !";
                }
            }


            return View(new PoneySeller.Models.Jumbotron());
        }

        int ExecuteCommande(string cmd)
        {
            int LigneModifie = 0;
            PoneySeller.Models.Users desUsagers = new PoneySeller.Models.Users(Session["MyPonies"]);

            LigneModifie = desUsagers.ExecuteCommandIntReturn(cmd);

            return LigneModifie;
        }
    }
}

PoneySeller/PoneySeller/Views/Shared/_Jumbotron.cshtml
@model PoneySeller.Models.Jumbotron

@switch (@Model.IDImage)
{
    case 1:
        <div class="jumbotron" style=" height: 300px; overflow: hidden; background-size: cover; background-image: url(/Images/Banner1.png); ">
        </div>
        break;

    case 2:
    <div class="jumbotron" style=" height: 300px; overflow: hidden; background-size: cover; background-image: url(/Images/Banner2.png); ">
    </div>
        break;

    case 3:
    <div class="jumbotron" style=" height: 300px; overflow: hidden; background-size: cover; background-image: url(/Images/Banner3.png); ">
    </div>
        break;

    case 4:
    <div class="jumbotron" style=" height: 300px; overflow: hidden; background-size: cover; background-image: url(/Images/Banner4.png); ">
    </div>
        break;

    case 5:
    <div class="jumbotron" style=" height: 300px; overflow: hidden; background-size: cover; background-image: url(/Images/Banner5.png); ">
    </div>
        break;

    case 6:
    <div class="jumbotron" style=" height: 300px; overflow: hidden; background-size: cover; background-image: url(/Images/Banner6.png); ">
    </div>
        break;

    case 7:
    <div class="jumbotron" style=" height: 300px; overflow: hidden; background-size: cover; background-image: url(/Images/Banner7.png); ">
    </div>
        break;

    case 8:
    <div class="jumbotron" style=" height: 300px; overflow: hidden; background-size: cover; background-image: url(/Images/Banner8.png); ">
    </div>
        break;

    case 9:
    <div class="jumbotron" style=" height: 300px; overflow: hidden; background-size: cover; background-image: url(/Images/Banner9.png); ">
    </div>
        break;

    case 10:
    <div class="jumbotron" style=" height: 300px; overflow: hidden; background-size: cover; background-image: url(/Images/Banner10.png); ">
    </div>
        break;

    default:
    <div class="jumbotron" style=" height: 300px; overflow: hidden; background-size: cover; background-image: url(/Images/Banner10.png); ">
    </div>
        break;

}

PoneySeller/PoneySeller/Views/Shared/_Layout.cshtml
@model PoneySeller.Models.Jumbotron

@functions
{
    public string[,] GetChevaux()
    {
        PoneySeller.Models.Users desUsagers = new PoneySeller.Models.Users(Session["MyPonies"]);
        string username = (string)Session["Username"];
        string[,] tab = desUsagers.GetChevaux(username);
        return tab;
    }
}

<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mon application ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("PoneySeller", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Accueil", "Index", "Home")</li>
                    
                    @if (Session["Username"] != "")
                    {
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                Gestion
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Nouveau cheval", "Gestion", "Gestion")</li>
                                @{
                        string[,] tab = GetChevaux();
                        if (tab.Length > 0)
                        {
                            for (int i = 0; i < tab.Length -1; i++)
                            {
                                <li>@Html.ActionLink(tab[i, 0], "Gestion", "Gestion", new { _idcheval = tab[i, 1] }, new { @id = "cheval" + i, @value = tab[i,0] })</li>
                            }
                        }
                                }
                            </ul>
                        </li>
                        <li>@Html.ActionLink("Profil", "Profil", "Gestion")</li>
                        <li>@Html.ActionLink("Deconnection", "Deconnection", "Home")</li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("Inscription", "Inscription", "Home")</li>
                    }
                </ul>
            </div>
        </div>
    </div>
    <div id="image">
        @{Html.RenderPartial("_Jumbotron", Model);}
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script type="text/javascript">
        var timer;
        function ChargeVuePartielle() {
            $.ajax({
                url: '@Url.Action("_Jumbotron")',
                type: 'GET',
                dataType: 'html',
                success: function (result) {
                    $('#image').html(result);
                }
            });
        }

        ChargeVuePartielle();
        $(function () {
            timer = window.setInterval("ChargeVuePartielle()", 5000);
        });
    </script>
</body>
</html>